version: "3.3"
services:
  postgres:
    image: "postgres:14.2"
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: postgres
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  dialer:
    build: api-dialer/
    image: api-dialer:1.1
    ports:
      - 8081:8081
    environment:
      - SERVER_PORT=8081
      - SERVER_SERVLET_CONTEXT_PATH=/api
      - NGROK_DOMAIN=https://2bb3-38-25-17-223.ngrok.io
      - APP_HOOK_URL=https://2bb3-38-25-17-223.ngrok.io/dialer/api/v1/call/incoming-event
      - APP_RINGCENTRAL_SUBSCRIPTIONTTL=86400
      - APP_RINGCENTRAL_URL=https://platform.devtest.ringcentral.com
      - APP_RINGCENTRAL_MAINACCOUNT_CLIENTID=<>
      - APP_RINGCENTRAL_MAINACCOUNT_CLIENTSECRET=<>
      - APP_RINGCENTRAL_MAINACCOUNT_USERNAME=<>
      - APP_RINGCENTRAL_MAINACCOUNT_PASSWORD=<>
      - APP_RINGCENTRAL_MAINACCOUNT_EXTENSION=<>
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres?stringtype=unspecified
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_PROPERTIES_HIBERNATE_SHOWSQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMATSQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULTSCHEMA=dialer
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect

  app:
    build: front-end/
    image: app:1.1
    ports:
      - "8080:8080"