server:
  port: 8081
  servlet:
    context-path: /api

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_schema: dialer
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?stringtype=unspecified
    username: postgres
    password: postgres

app:
  hook-url: ${NGROK_DOMAIN}/api/v1/call/incoming-event
  ring-central:
    subscription-ttl: 86400
    url: https://platform.devtest.ringcentral.com
    main-account:
      client-id: ~
      client-secret: ~
      username: ~
      password: ~
      extension: ~